dotnet/IMS/IMS/Controllers/API/ItemController.cs
using DAL;
using DAL.Models;
using IMS.Models.Database;
using IMS.Models.DataContracts;
using IMS.Models.DTO.Patch;
using IMS.Models.DTO.Request;
using IMS.Models.DTO.Response;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Http;
using System.Web.Http.Description;

namespace IMS.Controllers.API
{
    public class ItemController : ApiController
    {
        //Constructors

        public ItemController()
        {
            mItemRepository = new EntityRepository<Item>( new DBContext() );
        }

        //Methods

        [HttpGet]
        [ResponseType(typeof(IItem))]
        public async Task<IHttpActionResult> GetItem( int id )
        {
            var item = await mItemRepository
                .GetSingleOrDefaultWhere( queriedItem => queriedItem.ID == id );

            if (item != null)
            {
                var response = new ItemResponse();

                response.ParseExisting(item);

                return Ok(response);
            }
            else
            {
                return NotFound();
            }
        }

        [HttpGet]
        [ResponseType(typeof(List<IItem>))]
        public async Task<IHttpActionResult> GetItemList( int page = 1, int take = 10 )
        {
            var itemList = await mItemRepository
                .Paginate( page, take, order => order.ID );

            return Ok( itemList.ToPaginatedDto<ItemResponse, Item>() );
        }

        [HttpPost]
        [ResponseType(typeof(IItem))]
        public async Task<IHttpActionResult> CreateItem( [FromBody] ItemRequest itemRequest )
        {
            var item = itemRequest.ToDB();

            mItemRepository.Add(item);
            await mItemRepository.Save();

            return CreatedAtRoute("DefaultApi",
                new { ID = item.ID }, 
                item);
        }

        [HttpPatch]
        public async Task<IHttpActionResult> UpdateItem( int id, [FromBody]ItemPatchRequest itemRequest )
        {
            var item = await mItemRepository
                .GetSingleOrDefaultWhere( queriedItem => queriedItem.ID == id );

            if (item != null)
            {
                item = itemRequest.ToDB(item);

                mItemRepository.Edit(item);
                await mItemRepository.Save();

                return StatusCode(System.Net.HttpStatusCode.NoContent);
            }
            else
            {
                return NotFound();
            }
        }

        [HttpDelete]
        public async Task<IHttpActionResult> DeleteItem( int id )
        {
            var item = await mItemRepository
                .GetSingleOrDefaultWhere(queriedItem => queriedItem.ID == id);

            if (item != null)
            {
                mItemRepository.Delete(item);

                await mItemRepository.Save();

                return StatusCode(System.Net.HttpStatusCode.NoContent);
            }
            else
            {
                return StatusCode(System.Net.HttpStatusCode.NotFound);
            }
        }

        //Fields

        private EntityRepository<Item> mItemRepository;
    }
}

dotnet/IMS/IMS/Areas/App/Views/Index/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/App/Views/_LayoutMain.cshtml";
}

@section styles{ 
    <style type="text/css">
        [ng\:cloak], [ng-cloak], [data-ng-cloak], [x-ng-cloak], .ng-cloak, .x-ng-cloak{
            display: none !important;
        }
    </style>
    @Styles.Render("~/Content/css")
}

<div class="filter">
    <h3>Food List</h3>
    <div class="filter">
        <div class="dropdown">
            <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">
                Location Filter
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
                <li role="presentation" data-ng-repeat="location in locations.Items">
                    <a href="" data-ng-click="locationSortChanged(location.ID)" role="menuitem">{{location.Name}}</a>
                </li>
                <li role="presentation" class="divider"></li>
                <li role="presentation">
                    <a href="" role="menuitem">None</a>
                </li>
            </ul>

            <input type="text" class="" data-ng-model="filterText" placeholder="Search..." />
            <p class="pull-right">@Html.ActionLink("Add New...", "Index", "Item")</p>
        </div>
    </div>
</div>

<table class="food-list table table-responsive" data-ng-controller="MainController">
    <tr class="row">
        <th class="col-md-4">Food Name<span class="caret" data-ng-click="sortChanged('Name')" /></th>
        <th class="col-md-2">Location<span class="caret" data-ng-click="sortChanged('LocationID')" /></th>
        <th class="col-md-2">Expiration<span class="caret" data-ng-click="sortChanged('Expires')" /></th>
        <th class="col-md-2">Quantity<span class="caret" data-ng-click="sortChanged('Quantity')" /></th>
        <th class="col-md-2">Option</th>
    </tr>

    <tr class="row" data-ng-repeat="item in items.Items | filter:filterText | orderBy:sort">
        <td class="col-md-3">{{ item.Name }} - {{ item.Description }}</td>
        <td class="col-md-3" data-ng-bind="locationNames[{{ item.LocationID }}]"></td>
        <td class="col-md-2">{{ item.Expires | date: 'EEE, MMMM dd, yyyy' }}</td>
        <td class="col-md-2">{{ item.Quantity }}</td>
        <td class="col-md-2">
            <a href="/App/Item/Index/{{item.ID}}" class="glyphicon glyphicon-edit"></a> | <a class="glyphicon glyphicon-remove" data-ng-click="deleteItem(item)"></a>
        </td>
    </tr>
</table>

@section scripts{
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/angular")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/ims")
}